### ISSUE TITLE
Question: Is there a reason why a Rocky Linux 9.2 box is added to vagrant and not 9.3?

### ISSUE THREAD

**Issue by misterjaytee** [maxbyte9p/oelabox#4]
Hi,

The setup instructions recommend using a minimum of Rocky L:inux 9.3, but in the setup.yml we're askling Ansible to add a Rocky Linux 9.2 box to vagrant.  Is there a reason why a 9.2 box is used, or is this just an oversight?

**Comment by maxbyte9p** [comment]
This is a technical decision. I was having issues with the Rocky Linux 9.3 Vagrant box during development. At the time I was trying to upgrade from 9.2 to 9.3. The 9.3 Vagrant box may be working now, so I'll have to look into it.

**Comment by misterjaytee** [comment]
Thanks for the explanation, I was just curious nothing more.

**Comment by maxbyte9p** [comment]
Working on updating to Rocky 9.3 today.

**Comment by maxbyte9p** [comment]
So far it seems the Vagrant box for 9.3 is working, but I'll have to confirm if the right box is being used in my test VM.

**Comment by maxbyte9p** [comment]
> So far it seems the Vagrant box for 9.3 is working, but I'll have to confirm if the right box is being used in my test VM.

The DNS server is using 9.3 and the IPA server should be as well.

**Comment by maxbyte9p** [comment]
Gonna do a QA test post-commit.

**Comment by maxbyte9p** [comment]
QA test successful. Oela Box DNS server and IPA server now using Rocky Linux 9.3. Closing issue.
